// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iffumbosvkiwwxprjclc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZnVtYm9zdmtpd3d4cHJqY2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDk5OTgsImV4cCI6MjA2MzcyNTk5OH0.omk9R4J9VxmhNgZiyE_dK4PnFlsQAvvpgbYJoZG_CVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);